HOST: http://api.impactstory.org/

--- ImpactStory API, v1 ---
---
Welcome to the the ImpactStory API, version 1.

ImpactStory is a service that makes it quick and easy to view the impact of a wide range of research output. It goes beyond traditional measurements of research output -- citations to papers -- to embrace a much broader evidence of use across a wide range of scholarly output types. The system aggregates impact data from many sources and displays it in a single report, which is given a permaurl for dissemination and can be updated any time.

## javascript display embed code

If you are collecting metrics to display on a webpage, we recommend you use our javascript embed code.  [Details here](http://impactstory.org/api-docs).

## api base url

The base url of the REST API is [**http://api.impactstory.org/**](http://api.impactstory.org/).

You may notice the example code below uses an API base of http://impactstory.apiary.io --  we strongly recommend you replace this with our primary API base in your own code.

[CORS](http://en.wikipedia.org/wiki/Cross-origin_resource_sharing) is enabled.


## api keys and registered items

The most common workflow for the REST API is: 

1. Register an item with your API key.  We only start gathering metrics for an item once it has been registered. You can register an item through [POST /item](#post_item).
1. Read metrics on the item using [GET /item](#get_item).

You can combine steps 1 and 2 by setting the register=true flag on the GET request, like this: `GET /v1/item/:namespace/:id?key=YOURKEY&register=true`.

To request an ImpactStory API key, send an email to [team@impactstory.org](mailto:team@impactstory.org).  Your free key will allow you to register up to 1000 items.  Check out the pricing page for more information.



## rate limits

We do not impose rate limits at the moment, but we recommend delaying for a few seconds between each request.  It often takes us 5-10 seconds to collect metrics on an item the first time, due to the latency of our external metrics providers.

## data licenses

- All data in the ImpactStory API is released under as open a data licence as the primary data providers permit it to be.  We plan to inventory these licenses but haven't got an updated list at the moment, so please check with the primary data providers.
- Some providers allow us to show their metrics in our webapp but restrict its dissemination through our API.  Scopus citation data is available through our web application but not through the API.  CiteULike data is available through the API only in certain circumstances.
- Native ImpactStory data in the API (if there is any?) is released under a [CC0 waiver](http://creativecommons.org/publicdomain/zero/1.0/).  

## contact info

You can find our more about ImpactStory on our [webapp](http://impactstory.org/) and [FAQ](http://impactstory.org/faq).  
Contact us with questions or ideas, we'd love to hear from you!  [team@impactstory.org](mailto:team@impactstory.org) or [@impactstory](https://twitter.com/impactstory).  Thanks!    - Heather and Jason.

---

--
hello world
--
Check to make sure everything is working!  

See information above to get your own ImpactStory key after you've kicked the tires a bit.
Click the blue `/v1?key=YOURKEY` to see example return code.  Don't forget to replace the API base with **http://api.impactstory.org/** in your own code.
GET /v1?key=YOURKEY
< 200
< Content-Type: application/json
{
    "contact": "team@impactstory.org",
    "hello": "world",
    "message": "Congratulations! You have found the ImpactStory API.",
    "more-info": "http://impactstory.org/api-docs",
    "version": "cristhian"
}


--
add an item
<a id="post_item"></a>
Add an item to the ImpactStory system using the given namespace and id.  
Returns `201` even if the item is already in the database, because this call also registers the item as **active** under the supplied API Key (see top of this page for more information).

After POSTing an item, the item data can be obtained through [GET /item](#get_item) calls.
--
Add an item to the ImpactStory system using the given namespace and id.  There is no data payload to the POST.

This example uses a PubMed ID.  See the [GET /item](#get_item) section for more examples of valid namespaces and ids.
POST /v1/item/pmid/20807452?key=YOURKEY
< 201
"ok"




--
get item data
<a id="get_item"></a>
The following is a section of resources related to research items

- Returns `200` if the item metrics are available.
- Returns `210` if the item is currently being updated.  Updating an item usually takes less than ten seconds, but can take longer depending on ImpactServer 
server load or lag/errors from our metrics providers.  The API caller can poll slowly until a `200` is received.
- Returns `404` if item has not yet been added to ImpactStory.  In that case, a [POST /item](#post_item) call must be made before a GET call will be successful.
--
**Articles with PubMed IDs** Get metrics and biblio information on the item
will return a `210` while still updating, then a `200`
GET /v1/item/pmid/20807452?key=YOURKEY
< 200
< Content-Type: application/json
{
    "_id": "c5vh88e15ad42z9dmo1h08wi",
    "_rev": "8-6a7ece51607be9657d25cb979574e4db",
    "aliases": {
        "biblio": [
            {
                "authors": "Nyman, Vikberg, Smith, Boev\u00e9",
                "journal": "BMC Evolutionary Biology",
                "repository": "Springer (Biomed Central Ltd.)",
                "title": "How common is ecological speciation in plant-feeding insects? A 'Higher' Nematinae perspective",
                "year": 2010
            }
        ],
        "doi": [
            "10.1186/1471-2148-10-266"
        ],
        "pmid": [
            "20807452"
        ],
        "url": [
            "http://www.biomedcentral.com/1471-2148/10/266"
        ]
    },
    "biblio": {
        "authors": "Nyman, Vikberg, Smith, Boev\u00e9",
        "genre": "article",
        "journal": "BMC Evolutionary Biology",
        "repository": "Springer (Biomed Central Ltd.)",
        "title": "How common is ecological speciation in plant-feeding insects? A 'Higher' Nematinae perspective",
        "year": 2010
    },
    "created": "2012-11-23T22:00:37.209395",
    "currently_updating": false,
    "last_modified": "2012-11-23T22:00:44.087665",
    "metrics": {
        "citeulike:bookmarks": {
            "provenance_url": "http://www.citeulike.org/doi/10.1186/1471-2148-10-266",
            "static_meta": {
                "description": "Number of users who have bookmarked this item.",
                "display_name": "bookmarks",
                "icon": "http://citeulike.org/favicon.ico",
                "provider": "CiteULike",
                "provider_url": "http://www.citeulike.org/"
            },
            "values": {
                "WoS": {
                    "CI95_lower": 87,
                    "CI95_upper": 98,
                    "estimate_lower": 93,
                    "estimate_upper": 96
                },
                "raw": 1
            }
        },
        "mendeley:career_stage": {
            "provenance_url": "http://api.mendeley.com/research/common-ecological-speciation-plant-feeding-insects-higher-nematinae-perspective/",
            "static_meta": {
                "description": "Percent of readers by career stage, for top three career stages (csv, api only)",
                "display_name": "career stage, top 3 percentages",
                "icon": "http://www.mendeley.com/favicon.ico",
                "provider": "Mendeley",
                "provider_url": "http://www.mendeley.com/"
            },
            "values": {
                "raw": [
                    {
                        "name": "Ph.D. Student",
                        "value": 31
                    },
                    {
                        "name": "Post Doc",
                        "value": 16
                    },
                    {
                        "name": "Researcher (at an Academic Institution)",
                        "value": 9
                    }
                ]
            }
        },
        "mendeley:country": {
            "provenance_url": "http://api.mendeley.com/research/common-ecological-speciation-plant-feeding-insects-higher-nematinae-perspective/",
            "static_meta": {
                "description": "Percent of readers by country, for top three countries (csv, api only)",
                "display_name": "country, top 3 percentages",
                "icon": "http://www.mendeley.com/favicon.ico",
                "provider": "Mendeley",
                "provider_url": "http://www.mendeley.com/"
            },
            "values": {
                "raw": [
                    {
                        "name": "United States",
                        "value": 25
                    },
                    {
                        "name": "United Kingdom",
                        "value": 13
                    },
                    {
                        "name": "Brazil",
                        "value": 6
                    }
                ]
            }
        },
        "mendeley:discipline": {
            "provenance_url": "http://api.mendeley.com/research/common-ecological-speciation-plant-feeding-insects-higher-nematinae-perspective/",
            "static_meta": {
                "description": "Percent of readers by discipline, for top three disciplines (csv, api only)",
                "display_name": "discipline, top 3 percentages",
                "icon": "http://www.mendeley.com/favicon.ico",
                "provider": "Mendeley",
                "provider_url": "http://www.mendeley.com/"
            },
            "values": {
                "raw": [
                    {
                        "id": 3,
                        "name": "Biological Sciences",
                        "value": 78
                    },
                    {
                        "id": 12,
                        "name": "Environmental Sciences",
                        "value": 13
                    },
                    {
                        "id": 7,
                        "name": "Earth Sciences",
                        "value": 3
                    }
                ]
            }
        },
        "mendeley:groups": {
            "provenance_url": "http://api.mendeley.com/research/common-ecological-speciation-plant-feeding-insects-higher-nematinae-perspective/",
            "static_meta": {
                "description": "The number of groups who have added the article to their libraries",
                "display_name": "groups",
                "icon": "http://www.mendeley.com/favicon.ico",
                "provider": "Mendeley",
                "provider_url": "http://www.mendeley.com/"
            },
            "values": {
                "WoS": {
                    "CI95_lower": 81,
                    "CI95_upper": 96,
                    "estimate_lower": 88,
                    "estimate_upper": 93
                },
                "raw": 1
            }
        },
        "mendeley:readers": {
            "provenance_url": "http://api.mendeley.com/research/common-ecological-speciation-plant-feeding-insects-higher-nematinae-perspective/",
            "static_meta": {
                "description": "The number of readers who have added the article to their libraries",
                "display_name": "readers",
                "icon": "http://www.mendeley.com/favicon.ico",
                "provider": "Mendeley",
                "provider_url": "http://www.mendeley.com/"
            },
            "values": {
                "WoS": {
                    "CI95_lower": 94,
                    "CI95_upper": 99,
                    "estimate_lower": 98,
                    "estimate_upper": 98
                },
                "raw": 32
            }
        },
        "pubmed:pmc_citations": {
            "provenance_url": "http://www.ncbi.nlm.nih.gov/pubmed?linkname=pubmed_pubmed_citedin&from_uid=20807452",
            "static_meta": {
                "description": "The number of citations by papers in PubMed Central",
                "display_name": "citations",
                "icon": "http://www.ncbi.nlm.nih.gov/favicon.ico",
                "provider": "PubMed Central",
                "provider_url": "http://pubmed.gov"
            },
            "values": {
                "WoS": {
                    "CI95_lower": 87,
                    "CI95_upper": 96,
                    "estimate_lower": 93,
                    "estimate_upper": 93
                },
                "raw": 5
            }
        }
    },
    "type": "item"
}

**Articles or Datasets with DOIs** Get metrics and biblio information on the item
GET /v1/item/doi/10.1186/1756-0500-4-487?key=YOURKEY
< 200
{
    "_id": "c5vh88e15ad42z9dmo1h08wi",
    "_rev": "5-e02fab86d760d22e13b8812513b5cce0",
    "aliases": {
        "biblio": [
            {
                "authors": "Nyman, Vikberg, Smith, Boev\u00e9",
                "journal": "BMC Evolutionary Biology",
                "repository": "Springer (Biomed Central Ltd.)",
                "title": "How common is ecological speciation in plant-feeding insects? A 'Higher' Nematinae perspective",
                "year": 2010
            }
        ],
        "doi": [
            "10.1186/1471-2148-10-266"
        ],
        "pmid": [
            "20807452"
        ],
        "url": [
            "http://www.biomedcentral.com/1471-2148/10/266"
        ]
    },
    "biblio": {
        "authors": "Nyman, Vikberg, Smith, Boev\u00e9",
        "genre": "article",
        "journal": "BMC Evolutionary Biology",
        "repository": "Springer (Biomed Central Ltd.)",
        "title": "How common is ecological speciation in plant-feeding insects? A 'Higher' Nematinae perspective",
        "year": 2010
    },
    "created": "2012-11-23T22:00:37.209395",
    "currently_updating": true,
    "last_modified": "2012-11-23T22:00:43.085957",
    "metrics": {
        "mendeley:career_stage": {
            "provenance_url": "http://api.mendeley.com/research/common-ecological-speciation-plant-feeding-insects-higher-nematinae-perspective/",
            "static_meta": {
                "description": "Percent of readers by career stage, for top three career stages (csv, api only)",
                "display_name": "career stage, top 3 percentages",
                "icon": "http://www.mendeley.com/favicon.ico",
                "provider": "Mendeley",
                "provider_url": "http://www.mendeley.com/"
            },
            "values": {
                "raw": [
                    {
                        "name": "Ph.D. Student",
                        "value": 31
                    },
                    {
                        "name": "Post Doc",
                        "value": 16
                    },
                    {
                        "name": "Researcher (at an Academic Institution)",
                        "value": 9
                    }
                ]
            }
        },
        "mendeley:country": {
            "provenance_url": "http://api.mendeley.com/research/common-ecological-speciation-plant-feeding-insects-higher-nematinae-perspective/",
            "static_meta": {
                "description": "Percent of readers by country, for top three countries (csv, api only)",
                "display_name": "country, top 3 percentages",
                "icon": "http://www.mendeley.com/favicon.ico",
                "provider": "Mendeley",
                "provider_url": "http://www.mendeley.com/"
            },
            "values": {
                "raw": [
                    {
                        "name": "United States",
                        "value": 25
                    },
                    {
                        "name": "United Kingdom",
                        "value": 13
                    },
                    {
                        "name": "Brazil",
                        "value": 6
                    }
                ]
            }
        },
        "mendeley:discipline": {
            "provenance_url": "http://api.mendeley.com/research/common-ecological-speciation-plant-feeding-insects-higher-nematinae-perspective/",
            "static_meta": {
                "description": "Percent of readers by discipline, for top three disciplines (csv, api only)",
                "display_name": "discipline, top 3 percentages",
                "icon": "http://www.mendeley.com/favicon.ico",
                "provider": "Mendeley",
                "provider_url": "http://www.mendeley.com/"
            },
            "values": {
                "raw": [
                    {
                        "id": 3,
                        "name": "Biological Sciences",
                        "value": 78
                    },
                    {
                        "id": 12,
                        "name": "Environmental Sciences",
                        "value": 13
                    },
                    {
                        "id": 7,
                        "name": "Earth Sciences",
                        "value": 3
                    }
                ]
            }
        },
        "mendeley:groups": {
            "provenance_url": "http://api.mendeley.com/research/common-ecological-speciation-plant-feeding-insects-higher-nematinae-perspective/",
            "static_meta": {
                "description": "The number of groups who have added the article to their libraries",
                "display_name": "groups",
                "icon": "http://www.mendeley.com/favicon.ico",
                "provider": "Mendeley",
                "provider_url": "http://www.mendeley.com/"
            },
            "values": {
                "WoS": {
                    "CI95_lower": 81,
                    "CI95_upper": 96,
                    "estimate_lower": 88,
                    "estimate_upper": 93
                },
                "raw": 1
            }
        },
        "mendeley:readers": {
            "provenance_url": "http://api.mendeley.com/research/common-ecological-speciation-plant-feeding-insects-higher-nematinae-perspective/",
            "static_meta": {
                "description": "The number of readers who have added the article to their libraries",
                "display_name": "readers",
                "icon": "http://www.mendeley.com/favicon.ico",
                "provider": "Mendeley",
                "provider_url": "http://www.mendeley.com/"
            },
            "values": {
                "WoS": {
                    "CI95_lower": 94,
                    "CI95_upper": 99,
                    "estimate_lower": 98,
                    "estimate_upper": 98
                },
                "raw": 32
            }
        }
    },
    "type": "item"
}

**GitHub software repositories** Get metrics and biblio information on the item
GET /v1/item/github/egonw,cdk?key=YOURKEY
< 200
< Content-Type: application/json
{
    "_id": "k58vwwqzxxj0dq7ao4lchaxp",
    "_rev": "7-ba3054fac4f85f22a37bd3b88b102b34",
    "aliases": {
        "github": [
            "egonw,cdk"
        ],
        "title": [
            "cdk"
        ],
        "url": [
            "https://github.com/egonw/cdk"
        ]
    },
    "biblio": {
        "create_date": "2009-07-29T11:52:22Z",
        "description": "The Chemistry Development Kit",
        "genre": "software",
        "h1": "\n            ",
        "last_push_date": "2012-08-02T13:05:20Z",
        "owner": "egonw",
        "title": "cdk",
        "url": "https://github.com/egonw/cdk"
    },
    "created": "2012-08-02T10:40:10.941687",
    "currently_updating": false,
    "last_modified": "2012-09-26T00:30:45.049499",
    "metrics": {
        "github:forks": {
            "provenance_url": "https://github.com/egonw/cdk/network/members",
            "static_meta": {
                "description": "The number of people who have forked the GitHub repository",
                "display_name": "forks",
                "icon": "https://github.com/fluidicon.png",
                "provider": "GitHub",
                "provider_url": "http://github.com"
            },
            "values": {
                "raw": 28
            }
        },
        "github:watchers": {
            "provenance_url": "https://github.com/egonw/cdk/watchers",
            "static_meta": {
                "description": "The number of people who are watching the GitHub repository",
                "display_name": "watchers",
                "icon": "https://github.com/fluidicon.png",
                "provider": "GitHub",
                "provider_url": "http://github.com"
            },
            "values": {
                "raw": 31
            }
        }
    },
    "type": "item"
}

**SlideShare slides** Get metrics and biblio information on the item
GET /v1/item/url/http://www.slideshare.net/cavlec/who-owns-our-work?key=YOURKEY
< 200
< Content-Type: application/json
{
    "_id": "8yxrcdddi6npbhd675r7mqf1",
    "_rev": "7-9d98f382d10c8d5b63430dadfb69ec68",
    "aliases": {
        "title": [
            "Who owns our work?"
        ],
        "url": [
            "http://www.slideshare.net/cavlec/who-owns-our-work"
        ]
    },
    "biblio": {
        "created": "Tue Apr 13 03:42:30 -0500 2010",
        "genre": "slides",
        "h1": "Who owns our work?",
        "repository": "Slideshare",
        "title": "Who owns our work?",
        "username": "cavlec"
    },
    "created": "2012-08-14T19:59:21.805081",
    "currently_updating": false,
    "last_modified": "2012-08-14T19:59:51.597151",
    "metrics": {
        "slideshare:downloads": {
            "provenance_url": "http://www.slideshare.net/cavlec/who-owns-our-work",
            "static_meta": {
                "description": "The number of times the presentation has been downloaded",
                "display_name": "downloads",
                "icon": "http://www.slideshare.net/favicon.ico",
                "provider": "Slideshare",
                "provider_url": "http://www.slideshare.net/"
            },
            "values": {
                "raw": 36
            }
        },
        "slideshare:favorites": {
            "provenance_url": "http://www.slideshare.net/cavlec/who-owns-our-work",
            "static_meta": {
                "description": "The number of times the presentation has been favorited",
                "display_name": "favorites",
                "icon": "http://www.slideshare.net/favicon.ico",
                "provider": "Slideshare",
                "provider_url": "http://www.slideshare.net/"
            },
            "values": {
                "raw": 4
            }
        },
        "slideshare:views": {
            "provenance_url": "http://www.slideshare.net/cavlec/who-owns-our-work",
            "static_meta": {
                "description": "The number of times the presentation has been viewed",
                "display_name": "views",
                "icon": "http://www.slideshare.net/favicon.ico",
                "provider": "Slideshare",
                "provider_url": "http://www.slideshare.net/"
            },
            "values": {
                "raw": 2409
            }
        },
        "topsy:tweets": {
            "provenance_url": "http://topsy.com/www.slideshare.net/cavlec/who-owns-our-work?utm_source=otter",
            "static_meta": {
                "description": "Number of times the item has been tweeted",
                "display_name": "tweets",
                "icon": "http://twitter.com/phoenix/favicon.ico",
                "provider": "Topsy",
                "provider_url": "http://www.topsy.com/"
            },
            "values": {
                "raw": 3
            }
        }
    },
    "type": "item"
}

**Any url** Get metrics and biblio information on the item
GET /v1/item/url/http://www.carlboettiger.info?key=YOURKEY
< 200
< Content-Type: application/json
{
    "_id": "uosyks697znfvx9fb7nnmjav",
    "_rev": "5-4e2923c9aefd29fbde630b30f9b978e2",
    "aliases": {
        "url": [
            "http://www.carlboettiger.info"
        ]
    },
    "biblio": {
        "genre": "webpage",
        "h1": "Carl Boettiger",
        "title": "Carl Boettiger"
    },
    "created": "2012-10-02T10:09:50.051559",
    "currently_updating": false,
    "last_modified": "2012-10-02T20:14:00.848206",
    "metrics": {
        "facebook:likes": {
            "provenance_url": "",
            "static_meta": {
                "description": "Number of users who Liked a post about the item",
                "display_name": "likes",
                "icon": "http://www.facebook.com/favicon.ico",
                "provider": "Facebook",
                "provider_url": "http://www.facebook.com/"
            },
            "values": {
                "raw": 1
            }
        },
        "topsy:tweets": {
            "provenance_url": "http://topsy.com/www.carlboettiger.info?utm_source=otter",
            "static_meta": {
                "description": "Number of times the item has been tweeted",
                "display_name": "tweets",
                "icon": "http://twitter.com/phoenix/favicon.ico",
                "provider": "Topsy",
                "provider_url": "http://www.topsy.com/"
            },
            "values": {
                "raw": 4
            }
        }
    },
    "type": "item"
}


--
work with collections 

Collections are groups of items.  
Collections can be viewed in the webapp as http://impactstory.org/collection/`_id`.  For example: [http://impactstory.org/collection/kn5auf](http://impactstory.org/collection/kn5auf).
--
Create a collection of items.  
Data payload should contain a list of [namespace, id] pairs and a collection title, as JSON.  

`{"aliases": [["doi", "10.1371/journal.pcbi.1000361"], ["url", "http://www.carlboettiger.info/"]], "title": "My Collection"}`

Returns a collection object with a collection `_id` and status code `201`.  
POST /v1/collection?key=YOURKEY
> Content-Type: application/json;charset=utf-8
{"aliases": [["doi", "10.1371/journal.pcbi.1000361"], ["url", "http://www.carlboettiger.info/"]], "title": "My Collection"}
< 201
< Content-Type: application/json
{
    "collection": {
        "_id": "hr5mxg",
        "_rev": "1-63390a28dc923bb2df6c49aa2080fa6a",
        "alias_tiids": {
            "doi:10.1371/journal.pcbi.1000361": "8kgmw95as0o47piqee09k7of",
            "url:http://www.carlboettiger.info/": "1b2f4fc2bea711e1bdf912313d1a5e63"
        },
        "created": "2012-11-23T21:04:58.910101",
        "ip_address": "",
        "title": "My Collection",
        "type": "collection"
    },
}

Get the items and metadata associated with a collection.  Returns `210` when some items are currently updating, else `200`.
GET /v1/collection/kn5auf?key=YOURKEY
< 200
< Content-Type: application/json
{
    "_id": "kn5auf",
    "_rev": "15-0d1e7171fb34eefcfcdd275131b25a16",
    "created": "2012-06-25T09:21:12.673503",
    "title": "My Collection",
    "type": "collection"
    "items": [
        {
            "_id": "ql992e8bavpa1xdmncddlkee",
            "_rev": "179-6444a627050dfa65d3c3ed119e1db0eb",
            "type": "item",
            "created": "2012-08-07T16:34:59.689481",
            "currently_updating": false,
            "aliases": {..},
            "biblio": {..},
            "metrics": {..}
        }
    ]
}

-- metadata --

Get metadata for the providers that ImpactStory uses to obtain metrics, aliases, and bibliometric data.
GET /v1/provider?key=YOURKEY
< 200
< Content-Type: application/json
{
    "citeulike": {
        "descr": "CiteULike is a free service to help you to store, organise and share the scholarly papers you are reading.",
        "metrics": {
            "bookmarks": {
                "description": "Number of users who have bookmarked this item.",
                "display_name": "bookmarks",
                "icon": "http://citeulike.org/favicon.ico",
                "provider": "CiteULike",
                "provider_url": "http://www.citeulike.org/"
            }
        },
        "provides_aliases": false,
        "provides_metrics": true,
        "url": "http://www.citeulike.org/"
    },
    {
    "wikipedia": {
        "descr": "The free encyclopedia that anyone can edit.",
        "metrics": {
            "mentions": {
                "description": "The number of Wikipedia articles that mentioned this object.",
                "display_name": "mentions",
                "icon": "http://wikipedia.org/favicon.ico",
                "provider": "Wikipedia",
                "provider_url": "http://www.wikipedia.org/"
            }
        },
        "provides_aliases": false,
        "provides_metrics": true,
        "url": "http://www.wikipedia.org/"
    }
}

