HOST: http://api.impactstory.org/

--- ImpactStory v1 api ---
---
Welcome to the our version 1 API documentation.


## embed code

You may prefer to user our embed code.  See HERE for details.

## fresh metrics

We gather fresh metrics at the following times:
- the first time we have ever seen an item
- someone presses "update" on the web interface
- it is an item that has been POSTed by someone with an api key who has requested updates.  
Up to 1000 items can be kept updated for free: more will cost a small fee to facilitate sustainability of our service.

## keys

We only guarantee updated metrics for items with an ImpactStory-supplied api key. 
To request an ImpactStory-supplied api key, send an email to team@impactstory.org

## data licenses

## rate limiting


## contact info


---

--
hello world
--
GET /v1?key=YOURKEY
< 200
< Content-Type: application/json
{
    "contact": "team@impactstory.org",
    "hello": "world",
    "message": "Congratulations! You have found the ImpactStory API.",
    "more-info": "http://impactstory.org/api-docs",
    "version": "cristhian"
}


--
add an item to ImpactStory
<a id="post_item"></a>
The following is a section of resources related to research items
[link to get](#get_item)
--
Add a research item to the ImpactStory database.  Required to initiate collection of metrics.
POST /v1/item/pmid/22075173?key=YOURKEY
< 201
< Content-Type: application/json
{ "status": "created", "url": "/shopping-cart/2" }




--
get item data
<a id="get_item"></a>
The following is a section of resources related to research items
[link to post](#post_item)
--

**PubMed papers** Get metrics and biblio information on the item
will return a `210` while still updating, then a `200`
GET /v1/item/pmid/22075173?key=YOURKEY
< 210
< Content-Type: application/json
{
    "_id": "",
    "_rev": "",
    "aliases": {},
    "biblio":{},
    "metrics": {},
    "type": "item"
}
< 200
< Content-Type: application/json
{
    "_id": "",
    "_rev": "",
    "aliases": {},
    "biblio":{},
    "metrics": {},
    "type": "item"
}

*DOIs* Get metrics and biblio information on the item
GET /v1/item/doi/10.1186/1756-0500-4-487?key=YOURKEY
< 200
< Content-Type: application/json
{
    "_id": "",
    "_rev": "",
    "aliases": {},
    "biblio":{},
    "metrics": {},
    "type": "item"
}

##GitHub software repositories: Get metrics and biblio information on the item
GET /v1/item/github/egonw,cdk?key=EXAMPLE
< 200
< Content-Type: application/json
{
    "_id": "",
    "_rev": "",
    "aliases": {},
    "biblio":{},
    "metrics": {},
    "type": "item"
}

_SlideShare slides_ Get metrics and biblio information on the item
GET /v1/item/url/http://www.slideshare.net/cavlec/who-owns-our-work?key=EXAMPLE
< 200
< Content-Type: application/json
{
    "_id": "",
    "_rev": "",
    "aliases": {},
    "biblio":{},
    "metrics": {},
    "type": "item"
}


Get metrics and biblio information on the item
GET /v1/item/pmid/22075173?key=EXAMPLE
< 200
< Content-Type: application/json
{
}


-- work with collections --
This resource allows you to view information on collections
POST /v1/collection?key=YOURKEY
{ "cc": "12345678900", "cvc": "123", "expiry": "0112" }
< 200
{ "receipt": "/payment/receipt/1" }

Get metrics and biblio information on the item
GET /v1/collection/kn5auf?key=YOURKEY
< 200
< Content-Type: application/json
{ "items": [
  { "url": "/shopping-cart/1", "product":"2ZY48XPZ", "quantity": 1, "name": "New socks", "price": 1.25 }
] }
