#!/bin/bash
#
# chkconfig: 35 90 12
# description: Totalimpact backend server
#

# Find the absolute path for the current script
_my_name=`basename $0`
if [ "`echo $0 | cut -c1`" = "/" ]; then
  _my_path=`dirname $0`
else
  _my_path=`pwd`/`echo $0 | sed -e s/$_my_name//`
fi

# Find the root of the totalimpact directory
ROOTDIR=`dirname $_my_path`

# Change these to match your config
STATEDIR=$ROOTDIR/run
STARTUP_LOG=$ROOTDIR/logs/backend-startup.log
export TOTALIMPACT_CONFIG=$ROOTDIR/config/staging.cfg
export PYTHONPATH=.:$PYTHONPATH

start() {
    echo -n "Starting backend server: "
    is_running 
    return_val=$?
    if [ $return_val -eq 0 ]; then
        cd $ROOTDIR
        ./totalimpact/backend.py -d --startup-log=$STARTUP_LOG --pid=$STATEDIR/backend.pid
        echo "Started"
    else
        echo "Already running"
    fi
    echo
}

stop() {
    echo -n "Stopping backend server: "
    if [ -f $STATEDIR/backend.pid ]; then
        PID=`cat $STATEDIR/backend.pid`
		kill $PID
        while [ -e /proc/$PID ]; do sleep 0.1; done
		echo "Stopped"
	else 
		echo "Not running"	
	fi
	echo
}

is_running() { 
	if [ -f $STATEDIR/backend.pid ]; then
		ps `cat $STATEDIR/backend.pid` > /dev/null
		if [ $? -ne 0 ]; then
            return 0
		else 	
            return 1
		fi
	else
        return 0
	fi
}

status() {
    is_running
    if [ $? -eq 1 ]; then
        echo "Running"
    else
		echo "Stopped"
	fi
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status 
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
